import sys
import time
import os
import turtle

posponer = 0.1
timeleer = 5

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')
clear_screen()

#pantalla
wn = turtle.Screen()
wn.setup(width=700, height=350)
wn.bgcolor("orange")
wn.tracer(0)

texto = turtle.Turtle()
texto.speed(0)
texto.color("black")
texto.penup()
texto.hideturtle()
texto.goto(0,115)
texto.write("Bienvenido", align="center", font=("Courier", 25, "normal"))

texto1 = turtle.Turtle()
texto1.speed(0)
texto1.color("black")
texto1.penup()
texto1.hideturtle()
texto1.goto(0,90)
texto1.write("Para entrar en la calculadora debes crear una cuenta", align="center", font=("Courier", 16, "normal"))

texto2 = turtle.Turtle()
texto2.speed(0)
texto2.color("black")
texto2.penup()
texto2.hideturtle()
texto2.goto(0,60)
texto2.write("en la calculadora podras hacer cualquier tipo de operacion matematica", align="center", font=("Courier", 10, "normal"))

texto3 = turtle.Turtle()
texto3.speed(0)
texto3.color("black")
texto3.penup()
texto3.hideturtle()
texto3.goto(0,30)
texto3.write("¿Quieres crear una cuenta? si o no", align="center", font=("Courier", 20, "normal"))

time.sleep(timeleer)
timeleer = 2
clear_screen()
res = turtle.textinput(title="inicio", prompt="Respuestas",)
if res == "si":
    texto.clear()
    texto1.clear()
    texto2.clear()
    texto3.clear()
    texto = turtle.Turtle()
    texto.speed(0)
    texto.color("black")
    texto.penup()
    texto.hideturtle()
    texto.goto(0,70)
    texto.write("escribe un nombre de usuario", align="center",  font=("Courier", 20, "normal"))
    time.sleep(timeleer)
    usuario = turtle.textinput(title="registro", prompt="Respuesta")
    texto1 = turtle.Turtle()
    texto1.speed(0)
    texto1.color("black")
    texto1.penup()
    texto1.hideturtle()
    texto1.goto(0,30)
    texto1.write("escribe una contraseña numerica", align="center",  font=("Courier", 20, "normal"))
    time.sleep(timeleer)
    contraseña = turtle.numinput(title="registro", prompt="Respuesta",)
    for i in range(4):
        texto.clear()
        texto1.clear()  
        texto = turtle.Turtle()
        texto.speed(0)
        texto.color("black")
        texto.penup()
        texto.hideturtle()
        texto.goto(0,100)
        texto.write("Inicio de seccion", align="center", font=("Courier", 20, "normal"))
        texto1 = turtle.Turtle()
        texto1.speed(0)
        texto1.color("black")
        texto1.penup()
        texto1.hideturtle()
        texto1.goto(0,70)
        texto1.write("escribe tu nombre de usuario", align="center",  font=("Courier", 20, "normal"))
        time.sleep(timeleer)
        user = turtle.textinput(title="inicio", prompt="Respuesta") 
        if user == usuario:
            for i in range(4):
                texto2 = turtle.Turtle()
                texto2.speed(0)
                texto2.color("black")
                texto2.penup()
                texto2.hideturtle()
                texto2.goto(0,40)
                texto2.write("escribe tu Ccntraseña del usuario", align="center",  font=("Courier", 20, "normal"))
                time.sleep(timeleer)
                password = turtle.numinput(title="inicio", prompt="respuesta",)
                if password == contraseña:
                        timeleer = 8
                        texto.clear()
                        texto1.clear()
                        texto2.clear()
                        texto = turtle.Turtle()
                        texto.speed(0)
                        texto.color("black")
                        texto.penup()
                        texto.hideturtle()
                        texto.goto(0,125)
                        texto.write("bienvenidos a la calculadora "+usuario, align="center", font=("Courier", 20, "normal"))
                        texto1 = turtle.Turtle()
                        texto1.speed(0)
                        texto1.color("black")
                        texto1.penup()
                        texto1.hideturtle()
                        texto1.goto(0,110)
                        texto1.write("podras realizar operaciones de suma" ", resta, multiplicacion y divicion", align="center", font=("Courier", 10, "normal"))
                        texto2 = turtle.Turtle()
                        texto2.speed(0)
                        texto2.color("black")
                        texto2.penup()
                        texto2.hideturtle()
                        texto2.goto(0,80)
                        texto2.write("Que tipo de operacion quieres realizar "+usuario, align="center", font=("Courier", 15, "normal"))
                        texto3 = turtle.Turtle()
                        texto3.speed(0)
                        texto3.color("black")
                        texto3.penup()
                        texto3.hideturtle()
                        texto3.goto(0,40)
                        texto3.write("Suma, Resta, Multiplicacion, Divicion", align="center", font=("Courier", 20, "normal"))
                        time.sleep(timeleer)
                        for i in range(1000):
                            operacion = turtle.textinput(title="operacion", prompt="Respuesta")
                            if operacion == "suma":
                                timeleer = 3
                                texto.clear()
                                texto1.clear()
                                texto2.clear()
                                texto3.clear()
                                texto = turtle.Turtle()
                                texto.speed(0)
                                texto.color("black")
                                texto.penup()
                                texto.hideturtle()
                                texto.goto(0,125)
                                texto.write("Realicemos una suma "+usuario, align="center", font=("Courier", 20, "normal"))
                                texto1 = turtle.Turtle()
                                texto1.speed(0)
                                texto1.color("black")
                                texto1.penup()
                                texto1.hideturtle()
                                texto1.goto(0,100)
                                texto1.write("Escribe el primer numero a sumar "+usuario, align="center", font=("Courier", 20, "normal"))
                                time.sleep(timeleer)
                                num1 = turtle.numinput(title="primer numero", prompt="Respuesta")
                                texto2 = turtle.Turtle()
                                texto2.speed(0)
                                texto2.color("black")
                                texto2.penup()
                                texto2.hideturtle()
                                texto2.goto(0,75)
                                texto2.write("Escribe el segundo numero a sumar "+usuario, align="center", font=("Courier", 20, "normal"))
                                time.sleep(timeleer)
                                num2 = turtle.numinput(title="primer numero", prompt="Respuesta")
                                res = float(num1 + num2)
                                texto3 = turtle.Turtle()
                                texto3.speed(0)
                                texto3.color("black")
                                texto3.penup()
                                texto3.hideturtle()
                                texto3.goto(0,45)
                                texto3.write(f"El resultado es {res}", align="center", font=("Courier", 20, "normal"))
                            elif operacion == "resta":
                                timeleer = 3
                                texto.clear()
                                texto1.clear()
                                texto2.clear()
                                texto3.clear()
                                texto = turtle.Turtle()
                                texto.speed(0)
                                texto.color("black")
                                texto.penup()
                                texto.hideturtle()
                                texto.goto(0,125)
                                texto.write("Realicemos una resta "+usuario, align="center", font=("Courier", 20, "normal"))
                                texto1 = turtle.Turtle()
                                texto1.speed(0)
                                texto1.color("black")
                                texto1.penup()
                                texto1.hideturtle()
                                texto1.goto(0,100)
                                texto1.write("Escribe el primer numero a restar "+usuario, align="center", font=("Courier", 20, "normal"))
                                time.sleep(timeleer)
                                num1 = turtle.numinput(title="primer numero", prompt="Respuesta")
                                texto2 = turtle.Turtle()
                                texto2.speed(0)
                                texto2.color("black")
                                texto2.penup()
                                texto2.hideturtle()
                                texto2.goto(0,75)
                                texto2.write("Escribe el segundo numero a restar "+usuario, align="center", font=("Courier", 20, "normal"))
                                time.sleep(timeleer)
                                num2 = turtle.numinput(title="primer numero", prompt="Respuesta")
                                res = float(num1 + num2)
                                texto3 = turtle.Turtle()
                                texto3.speed(0)
                                texto3.color("black")
                                texto3.penup()
                                texto3.hideturtle()
                                texto3.goto(0,45)
                                texto3.write(f"El resultado es {res}", align="center", font=("Courier", 20, "normal"))
                            
                else:
                    sys.exit()
        else:
            sys.exit()
elif res == "no":
    sys.exit()
else:
    sys.exit()


while True:
    
    time.sleep(posponer)